spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
            - Path=/users/**
            - Path=/roles

        - id: catalog_service
          uri: lb://catalog-service
          predicates:
            - Path=/products
            - Path=/products/**
          filters:
            - name: JwtValidator

        - id: category_service
          uri: lb://category-service
          predicates:
            - Path=/categories
            - Path=/categories/**
          filters:
            - name: JwtValidator

logging:
  level:
    org:
      springframework: trace

security:
  access:
    secret:

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: