spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth_app
          uri: lb://auth-app
          predicates:
            - Path=/auth/**, /users/**, /roles

        - id: catalog_app
          uri: lb://catalog-app
          predicates:
            - Path=/products, /products/**
          filters:
            - name: JwtValidator

        - id: category_app
          uri: lb://category-app
          predicates:
            - Path=/categories, /categories/**
          filters:
            - name: JwtValidator

security:
  access:
    secret:

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: